"use client";

import { useState, useEffect, useRef } from "react";

const escapeComment = (str: string) => str.replace(/\n|\r/g, " ").replace(/\*\//g, "* /");
const escapeString = (str: string) => str.replace(/['"`$\\]/g, '\\$&').replace(/\n|\r/g, "");
import type { Hex, Address } from "viem";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import type { PermitDomain, PermitMessage } from "@/lib/eip712";
import type { SplitSignature } from "@/hooks/useVerifyPermit";
import type { TokenData } from "@/hooks/usePermitData";
import { Code, Copy, CheckCircle2 } from "lucide-react";

interface CodeExportProps {
  domain: PermitDomain;
  message: PermitMessage;
  signature: Hex;
  splitSig: SplitSignature;
  tokenData: TokenData;
  tokenAddress: Address;
}

export function CodeExport({
  domain,
  message,
  signature,
  splitSig,
  tokenData,
  tokenAddress,
}: CodeExportProps) {
  const [copiedTab, setCopiedTab] = useState<string | null>(null);

  const timeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  const safeName = escapeComment(tokenData.name);
  const safeSymbol = escapeComment(tokenData.symbol);
  
  const chainName = domain.chainId === 30 ? "rootstock" : domain.chainId === 31 ? "rootstockTestnet" : "mainnet";

  const solidityCode = `// SPDX-License-Identifier: MIT
// Permit call for ${safeName} (${safeSymbol})
// Generated by Permit-Wiz

// Token: ${tokenAddress}
// Chain ID: ${domain.chainId}

IERC20Permit token = IERC20Permit(${tokenAddress});

token.permit(
    ${escapeString(message.owner)},  // owner
    ${escapeString(message.spender)},  // spender
    ${message.value.toString()},  // value (raw, ${tokenData.decimals} decimals)
    ${message.deadline.toString()},  // deadline (unix timestamp)
    ${splitSig.v},  // v
    ${escapeString(splitSig.r)},  // r
    ${escapeString(splitSig.s)}   // s
);

// After permit, call transferFrom:
// token.transferFrom(owner, spender, ${message.value.toString()});`;

  const jsCode = `// Permit call using Viem
// Generated by Permit-Wiz
// Token: ${safeName} (${safeSymbol}) on Chain ${domain.chainId}

import { createPublicClient, createWalletClient, custom, http } from 'viem';
import { ${chainName} } from 'viem/chains';

const TOKEN_ADDRESS = '${tokenAddress}';

// Setup clients (assuming injected provider like MetaMask)
const walletClient = createWalletClient({
  chain: ${chainName},
  transport: custom(window.ethereum)
});

// The signed permit parameters
const permitParams = {
  owner: '${escapeString(message.owner)}',
  spender: '${escapeString(message.spender)}',
  value: ${message.value.toString()}n,
  deadline: ${message.deadline.toString()}n,
  v: ${splitSig.v},
  r: '${escapeString(splitSig.r)}',
  s: '${escapeString(splitSig.s)}',
};

// Execute the permit transaction
// Note: You must request accounts first: await walletClient.requestAddresses();
const [account] = await walletClient.requestAddresses();

const hash = await walletClient.writeContract({
  address: TOKEN_ADDRESS,
  account,
  abi: [
    {
      name: 'permit',
      type: 'function',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'owner', type: 'address' },
        { name: 'spender', type: 'address' },
        { name: 'value', type: 'uint256' },
        { name: 'deadline', type: 'uint256' },
        { name: 'v', type: 'uint8' },
        { name: 'r', type: 'bytes32' },
        { name: 's', type: 'bytes32' },
      ],
      outputs: [],
    },
  ],
  functionName: 'permit',
  args: [
    permitParams.owner,
    permitParams.spender,
    permitParams.value,
    permitParams.deadline,
    permitParams.v,
    permitParams.r,
    permitParams.s,
  ],
});

console.log('Permit tx hash:', hash);`;

  const signatureCode = `// Full Signature
const signature = '${escapeString(signature)}';

// Split Components
const v = ${splitSig.v};
const r = '${escapeString(splitSig.r)}';
const s = '${escapeString(splitSig.s)}';

// Domain (EIP-712)
const domain = ${JSON.stringify(domain, null, 2)};

// Message
const message = {
  owner: '${escapeString(message.owner)}',
  spender: '${escapeString(message.spender)}',
  value: '${message.value.toString()}',
  nonce: '${message.nonce.toString()}',
  deadline: '${message.deadline.toString()}',
};`;

  const copyCode = async (code: string, tab: string) => {
    try {
      if (typeof navigator !== "undefined" && navigator.clipboard) {
        await navigator.clipboard.writeText(code);
        setCopiedTab(tab);
        if (timeoutRef.current) clearTimeout(timeoutRef.current);
        timeoutRef.current = setTimeout(() => setCopiedTab(null), 2000);
      }
    } catch (err) {
      if (process.env.NODE_ENV !== "production") {
        console.error("Failed to copy code to clipboard", err);
      }
    }
  };

  return (
    <Card className="border-border/40 bg-card/50 backdrop-blur-sm">
      <CardHeader className="pb-4">
        <div className="flex items-center gap-2">
          <Code className="h-5 w-5 text-orange-400" />
          <CardTitle className="text-lg">Code Export</CardTitle>
        </div>
        <CardDescription>
          Copy the verified permit call directly into your project.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="solidity" className="w-full">
          <TabsList className="w-full bg-muted/30">
            <TabsTrigger value="solidity" className="flex-1">
              Solidity
            </TabsTrigger>
            <TabsTrigger value="javascript" className="flex-1">
              JavaScript (Viem)
            </TabsTrigger>
            <TabsTrigger value="raw" className="flex-1">
              Raw Data
            </TabsTrigger>
          </TabsList>

          <TabsContent value="solidity" className="mt-4 space-y-2">
            <div className="flex justify-end">
              <CopyButton
                onClick={() => copyCode(solidityCode, "solidity")}
                copied={copiedTab === "solidity"}
              />
            </div>
            <pre className="max-h-96 overflow-auto rounded-lg border border-border/30 bg-[#0d1117] p-4 text-xs leading-relaxed text-emerald-300/90">
              {solidityCode}
            </pre>
          </TabsContent>

          <TabsContent value="javascript" className="mt-4 space-y-2">
            <div className="flex justify-end">
              <CopyButton
                onClick={() => copyCode(jsCode, "js")}
                copied={copiedTab === "js"}
              />
            </div>
            <pre className="max-h-96 overflow-auto rounded-lg border border-border/30 bg-[#0d1117] p-4 text-xs leading-relaxed text-sky-300/90">
              {jsCode}
            </pre>
          </TabsContent>

          <TabsContent value="raw" className="mt-4 space-y-2">
            <div className="flex justify-end">
              <CopyButton
                onClick={() => copyCode(signatureCode, "raw")}
                copied={copiedTab === "raw"}
              />
            </div>
            <pre className="max-h-96 overflow-auto rounded-lg border border-border/30 bg-[#0d1117] p-4 text-xs leading-relaxed text-amber-300/90">
              {signatureCode}
            </pre>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}

function CopyButton({
  onClick,
  copied,
  label = "Copy code to clipboard",
}: {
  onClick: () => void;
  copied: boolean;
  label?: string;
}) {
  return (
    <Button
      variant="ghost"
      size="sm"
      onClick={onClick}
      aria-label={copied ? "Code copied" : label}
      className="h-auto px-2 py-1 text-xs text-muted-foreground hover:text-foreground"
    >
      {copied ? (
        <>
          <CheckCircle2 className="mr-1 h-3 w-3 text-emerald-400" aria-hidden="true" />
          Copied!
        </>
      ) : (
        <>
          <Copy className="mr-1 h-3 w-3" aria-hidden="true" />
          Copy
        </>
      )}
    </Button>
  );
}
